### PR TITLE
[wip] ensure prerequisites for nokogiri are installed

### PR DESCRIPTION
**Pull request by JonRowe**

### CODE REVIEW

**Comment by myronmarston** [comment]
Why do we need nokogiri for rspec-expectations? I thought we only needed it for rspec-rails.

**Comment by JonRowe** [comment]
@myronmarston I think it's coming from the `rspec-core` build in this instance (which will use it for validating the html formatter) but it's failing the build here, my goal was if this worked would be just to add the prerequirests (`libxml2`) to all the travis builds...

**Comment by myronmarston** [comment]
Thanks for explaining.  I hadn't seen the build failures yet.

It looks like Nokogiri 1.6.6.3 was released today; given this is a new problem, my guess is that it's only a problem on 1.6.6.3.  A simple solution might be to lock nokogiri in rspec-core's gemfile to `< 1.6.6.3`.

**Comment by JonRowe** [comment]
Fixed by pinning nokogiri instead, FWIW it's apparently an issue with docker (which travis uses under the hood IIRC) and nokogiri, hopefully they'll fix it :/

**Pull request closed without merging**
