### PR TITLE
Prevent infinite ranges blowing up matcher descriptions

### PR DESCRIPTION
**Pull request by JonRowe**
See #755, this is just for Travis.

### CODE REVIEW

**Comment by myronmarston** [comment]
Hmm, travis isn't building this.  It may have to do with the fact that HEAD of this branch has the same commit SHA so travis doesn't think it's new.  You can always `git commit --amend` and leave the commit message unchanged just to update the SHA.

**Comment by JonRowe** [comment]
Well this was already an amended (squashed) commit, and doing it again (note new sha) hasn't triggered this

**Comment by JonRowe** [comment]
I'd blame our new branch config but it hasn't triggered Appveyor either...

**Comment by myronmarston** [comment]
Closing in favor of #757.

**Pull request closed without merging**
