### PR TITLE
Raise error deprecation

### PR DESCRIPTION
**Pull request by williamcodes**
Modify deprecation warning error as per discussion in issue #286

### CODE REVIEW

**Comment by williamcodes** [comment]
What is AppVeyor and how do I tell why it's failing?

**Comment by myronmarston** [comment]
AppVeyor is a CI service we use to test RSpec on Windows.  We use travis to test RSpec on posix systems.

AppVeyor reports a failure if a PR isn't mergable (because what it tries to build is the merge commit of a PR).  Travis likewise tries to build a merge commit, but unlike AppVeyor, it simply doesn't report anything if your PR isn't mergable.

Looking at your PR...something funny happened.   It has 63 commits, some as old as 2 years old!  I'm not sure what you did...but to fix it, here's my suggestion:

```
git checkout master
git reset --hard
git pull --rebase
git checkout -b raise-error-deprecation-try-2
git cherry-pick 3a78f2b691035643f14adaf7fc9512bd70832cb9
git push origin raise-error-deprecation-try-2 -u
```

That'll create a new branch (`raise-error-deprecation-try-2`) that should not suffer from this problem.  Close this PR and open a new one based on that branch and it should be mergable and will build as normal.

**Comment by williamcodes** [comment]
Looks like I made the pull request to master instead of to version 2.14. This deprecation warning no longer exists on master because presumably you all stopped supporting whatever you deprecated when you bumped your major version.

I've made [another pull request](https://github.com/rspec/rspec-expectations/pull/896), but now that I think about it, you would probably need this change to happen to all subsequent 2.x releases, and are likely not accepting any changes to 2.x unless they present some sort of massive security concern, is that correct?

If the wording I was confused by doesn't exist anymore anywhere in RSpec, perhaps I should abandon this pull request. Thoughts?

**Comment by JonRowe** [comment]
We're not maintaining 2.x except to improve the upgrade path with 2.99, so I closed your other PR, if you want to change this in 3.x I'd be happy to help... I'm pretty sure the warning still exists I'll find it for you.

**Comment by JonRowe** [comment]
Yes, in master this was changed to be a warning that can be supressed, rather than a deprecation, it prints out:

```
WARNING: Using `expect { }.not_to raise_error(SpecificErrorClass)` risks false positives, since literally any other error would cause the expectation to pass, including those raised by Ruby (e.g. NoMethodError, NameError and ArgumentError), meaning the code you are intending to test may not even get reached. Instead consider using `expect {}.not_to raise_error`. This message can be supressed by setting: `RSpec::Expectations.configuration.warn_about_potential_false_positives = false`. Called from __FILE__:122:in `block (3 levels) in <top (required)>'
```

So with your change this would read:

```
WARNING: Using `expect { }.not_to raise_error(SpecificErrorClass)` risks false positives, since literally any other error would cause the expectation to pass, including those raised by Ruby (e.g. NoMethodError, NameError and ArgumentError), meaning the code you are intending to test may not even get reached. Instead consider using `expect {}.not_to raise_error` or `expect { }.to raise_error(DifferentSpecificErrorClass)`. This message can be supressed by setting: `RSpec::Expectations.configuration.warn_about_potential_false_positives = false`. Called from __FILE__:122:in `block (3 levels) in <top (required)>'
```

The code in question is at: lib/rspec/matchers/built_in/raise_error.rb:134

**Comment by williamcodes** [comment]
https://github.com/rspec/rspec-expectations/pull/897

**Pull request closed without merging**
