### PR TITLE
Generating diffs of large objects consumes enough CPU to freeze the average computer

### PR DESCRIPTION
**Pull request by JonRowe**
When certain expectations fail RSpec will try to generate diff of the expected and received values. Usually this works fine, except when those values are 6000 line long HTML documents parsed using Nokogiri (or any other operation using big objects). In such a case generating a diff will consume enough CPU usage to at least freeze my Macbook Pro, requiring a hard reboot to make it usable again.

Repro: https://gist.github.com/YorickPeterse/ff2919edb411d9b2689e

Save the script somewhere and run it using either `ruby script.rb` or `rspec script.rb`. If you're using a laptop you'll want to take it off your lap and plug in the charger first.

### CODE REVIEW

**Comment by JonRowe** [comment]
Let's see what Travis does..

**Comment by YorickPeterse** [comment]
I'm not sure how that would be related. A colleague of mine ran the script on OS X and it produced the same pattern: it hangs while sucking up 100% CPU. They're also using Nokogiri 1.6.6.2.

**Comment by JonRowe** [comment]
> I'm not sure how that would be related. A colleague of mine ran the script on OS X and it produced the same pattern: it hangs while sucking up 100% CPU. They're also using Nokogiri 1.6.6.2.

From memory, nokogiri bundles libxml2 in certain situations where it would be unavailable (e.g. OSX) but on linux it uses the platform library. This is the one key difference I can think of between OSX and linux that is causing this to fail for you.

**Comment by JonRowe** [comment]
Hmm, no theres more to it. The autorun example actually doesn't blow up for me, but inserting it into RSpecs own spec suite does.

**Comment by JonRowe** [comment]
Converting the nokogiri objects to string manually actually causes the spec to pass, converting them to their inspect output causes the spec to fail with a diff correctly.

**Comment by JonRowe** [comment]
So I can recreate this with `PP.pp @doc_1`, so it's actually not strictly an RSpec issue (its also code in rspec-support not rspec-expectations FWIW @rspec/rspec) pondering what to do about this, if an object can't be safely coerced into a string using pretty print...

**Comment by JonRowe** [comment]
So the nokogiri document when pretty printed comes out closer to 50000 lines, and it's possible to replicate this standalong, closing in favour of rspec/rspec-support#196

**Pull request closed without merging**
